name: Release

on:
  push:
    # branches:
    #   - main
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v1
        with:
          fetch-depth: 100
      - name: Release Job
        uses: BigWigsMods/packager@master
      # - name: Classic
      #   uses: BigWigsMods/packager@master
      #   with:
      #     args: -g classic
      # - name: Burning Crusade Classic
      #   uses: BigWigsMods/packager@master
      #   with:
      #     args: -g bcc
  notify-discord:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: jhogendorn/djs-actions
        with:
          id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          title: ElvUI SplitActionBars Release ${{ github.context.payload.release.tag_name }}
          description: ElvUI SplitActionBars version ${{ github.context.payload.release.tag_name }} has been released.  You can use your wow addon client that can download from wago addons or curse to update.
          footer: Addons by Repooc
          timestamp: true
